### ISSUE TITLE
Some pointers

### ISSUE THREAD

**Issue by IzzySoft** [gsora/TootApp#2]
Hi,

thumbs up for jumping on the Mastodon train :) Just checked your `releases/` and noticed they all come with the very same `versionCode` and `versionName`:

    package: name='xyz.gsora.toot' versionCode='1' versionName='1.0' platformBuildVersionName='7.1.1'

This makes it difficult to update once installed, and difficult to see if there's a new version. Would you mind increasing these two values with each new version? Also, placing a License would be a good idea.

Carry on! :)

**Comment by gsora** [comment]
Thank you for pointing out that Gradle issue, I'm still learning how the entire ecosystem works.

Regarding versioning, right now the application is not in an usable usable state, meaning that not all the needed functionality for daily usage are implemented. 

All the builds released are just "tests", sometimes I don't see bugs or strange behaviors while other people might.

Licensing is an issue I'll address later today, this repo was private first, and I completely forgot about it.

**Comment by IzzySoft** [comment]
Always glad to help! Even though the app is not yet "production ready", it would help if versions are numbered differently (you could start with a `versionName` of `0.1.0` to indicate the "not ready state", and `versionCode` is an internal thing anyway). Makes it easier to keep them apart, included issues reported referencing which one was installed. Plus, [updates could be automated](https://apt.izzysoft.de/fdroid/index/apk/xyz.gsora.toot) :smile_cat:

Please let me know when you've set that up (including having added a license), simply updating this issue will do for that, so I can adjust it on my end.

**Comment by gsora** [comment]
Since tagged releases are uploaded by Travis automagically to GitHub release, I think I'll use the tag itself as version number for now, I just have to figure out a way to let Gradle see it.

**Comment by IzzySoft** [comment]
Version *numbers* better be numeric :) Otherwise, how to tell which one is newer? Why not simply start with `0.1.<versionCode>` and increment the `<versionCode> with each subsequent release (which you had to do anyway), until reaching "stable state" and declaring it `1.0.0`?

> I'll close this issue as soon as I've everything set up 😊

Sure, good point that :+1:

**Comment by gsora** [comment]
I've officially declared this project to be licensed under the MIT license, and I've fixed Gradle to output a debug release with an appropriate version code as you suggested; you can find an example in the latest release.

What do you think?

**Comment by IzzySoft** [comment]
Sounds great! I'll check ASAP and let you know how it looks. Currently I'm not at my machine, so I cannot look deeper. Thanks a lot already!

**Comment by gsora** [comment]
Should be fixed now 👍

**Comment by IzzySoft** [comment]
Superb! Please let me know when you've tagged it, I'll check then. Once it's working, I can switch it to automatic :)

**Comment by IzzySoft** [comment]
Well, looks like it's still not fixed – so my script fails to pick it, and even if it'd succeed the repo build would fail. Let's take a look at the latest package. Current info is:

    package: name='xyz.gsora.toot' versionCode='1' versionName='0.1.debug.a3c475b' platformBuildVersionName='7.1.1'

Expected: a `versionCode` larger than 1 (it's not the first version, even if in beta – so this number should simply be increased with each new version you put online), and an "evaluable" `versionName` (i.e. one where by looking at it you can say which version is newer – not possible when using hashes). Looking at the history on the `releases/` page, an example how it could look for the currently latest package:

    package: name='xyz.gsora.toot' versionCode='9' versionName='0.1.20170518' platformBuildVersionName='7.1.1'

Of course, the `versionName` suggested still isn't ideal – but something easily "generated" and meeting the criteria. Should do for the "early stage".

**Comment by gsora** [comment]
Uh-oh, I expected it to be fixed as well 😕

Right now I'm too occupied with school stuff, I'll figure something out as soon as I have some free time.

**Comment by IzzySoft** [comment]
Whenever you're ready :smile_cat: 

BTW: While on it, please check what suspicious thing has slipped in with one of the last versions. I've let VirusTotal run on it, and [got a PUP reported](https://www.virustotal.com/de/file/cbf422e77c03982612c2bcba1fe1701bd03cbb3e91f1fe4d66a4e5d15ca95e13/analysis/1495224293/). Wasn't there with the last version I've checked about 10 days ago.

**Comment by gsora** [comment]
I've noticed that too.

I usually develop on my Gentoo notebook only some commits (and builds) come from my Windows desktop. 

I don't think some malware on any of my computer is tapping my code with unwanted code etc... Maybe a false positive?

**Comment by IzzySoft** [comment]
Nothing to do with "explicit malware" or a virus. PUP = Potential Unwanted Program. Usually refers to specific ad or analytics code, or any similar "annoyance". Remember having added something in that context?

WhiteArmor overdoes it a bit with that, throwing in their PUPs as if they were dangerous malware. While they might be annoyances, they've got nothing to do in a malware report IMHO. Though I understand both belong into the category "unwanted", malware is a sub-category of "unwanted" and not the other way around. Still, all most users see is "Alert!"…

**Comment by gsora** [comment]
I might have some Google-related libraries as dependency, but just because Android Studio loves to place these automagically in any new project, they'll be removed soon.

I don't want any form of transparent tracking or ads in this application 🙂

**Comment by IzzySoft** [comment]
Currently it contains GoogleAds and DoubleClick indeed. But those two have been present in the previous version as well. If that was not intended, removal is always welcome (so that "AntiFeature" box can be removed). Glad to read you don't like that either :innocent:

**Comment by IzzySoft** [comment]
Just wondering: Is this project still "alive" (and just paused) – or is it rather ended?
